optionsFile: null
printHelp: false
classPath:
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/HdrHistogram-2.1.12.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/HikariCP-3.4.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/LatencyUtils-2.0.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/aliyun-sdk-oss-2.5.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/animal-sniffer-annotations-1.14.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/aspectjweaver-1.9.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/byte-buddy-1.10.10.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/checker-qual-2.0.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/classmate-1.5.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/commons-beanutils-1.8.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/commons-codec-1.14.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/commons-collections-3.2.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/commons-lang-2.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/commons-logging-1.1.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/druid-1.1.23.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/druid-spring-boot-starter-1.1.23.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/error_prone_annotations-2.1.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/ezmorph-1.0.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/guava-25.1-jre.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/hibernate-validator-6.1.5.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/httpclient-4.5.12.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/httpcore-4.4.13.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/hutool-all-5.4.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/j2objc-annotations-1.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-annotations-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-core-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-databind-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-datatype-jdk8-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-datatype-jsr310-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jackson-module-parameter-names-2.11.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jakarta.annotation-api-1.3.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jakarta.el-3.0.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jakarta.validation-api-2.0.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jboss-logging-3.4.1.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jcip-annotations-1.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jdom-1.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jjwt-0.9.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/json-lib-2.4-jdk15.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jsqlparser-3.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jsr305-3.0.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/jul-to-slf4j-1.7.30.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/lettuce-core-5.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/log4j-api-2.13.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/log4j-to-slf4j-2.13.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/logback-classic-1.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/logback-core-1.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/logstash-logback-encoder-5.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/lombok-1.18.12.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mapstruct-1.2.0.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/micrometer-core-1.5.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/minio-7.1.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mybatis-3.5.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mybatis-generator-core-1.4.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mybatis-spring-2.0.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mybatis-spring-boot-autoconfigure-2.1.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mybatis-spring-boot-starter-2.1.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/mysql-connector-java-8.0.20.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-buffer-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-codec-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-common-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-handler-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-resolver-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/netty-transport-4.1.49.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/okhttp-3.14.8.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/okio-1.17.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/pagehelper-5.2.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/pagehelper-spring-boot-autoconfigure-1.3.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/pagehelper-spring-boot-starter-1.3.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/protobuf-java-3.6.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/reactive-streams-1.0.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/reactor-core-3.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/simple-xml-safe-2.7.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/slf4j-api-1.7.30.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/snakeyaml-1.26.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spotbugs-annotations-4.0.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-aop-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-beans-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-actuator-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-autoconfigure-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-configuration-processor-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-actuator-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-aop-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-data-redis-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-jdbc-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-json-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-logging-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-security-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-tomcat-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-validation-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-boot-starter-web-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-context-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-context-support-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-core-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-data-commons-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-data-keyvalue-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-data-redis-2.3.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-expression-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-jcl-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-jdbc-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-oxm-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-plugin-core-1.2.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-plugin-metadata-1.2.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-security-config-5.3.2.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-security-core-5.3.2.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-security-web-5.3.2.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-tx-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-web-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/spring-webmvc-5.2.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-core-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-schema-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-spi-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-spring-web-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-swagger-common-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-swagger-ui-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/springfox-swagger2-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/swagger-annotations-1.6.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/swagger-models-1.6.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/tomcat-embed-core-9.0.35.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/lib/tomcat-embed-websocket-9.0.35.jar

  #  - ./java-benchmarks/java-sec-code/spring-web-6.1.4.jar
#  spring-context-support-5.1.4.RELEASE.jar

#appClassPath: java-benchmarks/java-sec-code/target/classes
appClassPath:
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-admin-1.0/BOOT-INF/classes
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-common-1.0
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-mbg-1.0
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/mall-security-1.0
#  - ./java-benchmarks/java-sec-code-new/java-sec-code/demo/target/classes
mainClass: com.macro.mall.MallAdminApplication
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: true
scope: REACHABLE
nativeModel:  false
planFile: null
analyses:
  #  ir-dumper: ;
  #  pta: cs:ci;implicit-entries:true;merge-string-constants:null;reflection-inference:solar;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:config/common/taint-config.yml;
  #  pta: cs:ci;taint-config:config/common/taint-config.yml;
  #  pta: cs:ci;plugins:[pascal.taie.analysis.pta.plugin.taint.SpringBootHandler,pascal.taie.analysis.pta.plugin.taint.DependencyInjectionHandler];implicit-entries:true;distinguish-string-constants:null;reflection-inference:solar;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:taint-config.yml;
  #  pta: cs:ci;plugins:[pascal.taie.analysis.pta.plugin.taint.SpringBootHandler,pascal.taie.analysis.pta.plugin.taint.DependencyInjectionHandler];implicit-entries:true;distinguish-string-constants:null;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:config/common/taint-config.yml;
  pta: cs:3-call;implicit-entries:false;taint-config:config/mall-admin/mall-admin1.yml;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
