optionsFile: null
printHelp: false
classPath:
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/UserAgentUtils-1.13.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activation-1.1.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-bpmn-converter-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-bpmn-model-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-common-rest-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-crystalball-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-diagram-rest-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-engine-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-explorer-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-image-generator-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-json-converter-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-modeler-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-process-validation-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/activiti-spring-5.21.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/analyzer-2012_u6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/aopalliance-1.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/apache-ant-zip-2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/asm-4.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/aspectjrt-1.7.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/aspectjweaver-1.7.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/avalon-framework-api-4.3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/avalon-framework-impl-4.3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-anim-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-awt-util-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-bridge-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-codec-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-css-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-dom-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-ext-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-gvt-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-js-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-parser-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-script-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-svg-dom-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-svggen-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-transcoder-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-util-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/batik-xml-1.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/cas-client-core-3.2.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/cglib-3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ckfinder-2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ckfinderplugin-fileeditor-2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ckfinderplugin-imageresize-2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/classmate-1.1.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-beanutils-1.9.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-codec-1.9.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-collections-3.2.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-dbcp-1.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-email-1.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-fileupload-1.3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-io-2.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-lang3-3.3.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-logging-1.0.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-pool-1.5.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/commons-pool2-2.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/core-2.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/dom4j-1.6.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/dozer-5.5.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/druid-1.0.18.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ehcache-core-2.6.11.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ehcache-web-2.0.4.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/fop-0.94.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/freemarker-2.3.20.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/groovy-all-2.4.5.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/guava-17.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/h2-1.3.176.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/hamcrest-core-1.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/hibernate-validator-5.2.4.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/imgscalr-lib-4.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jackson-annotations-2.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jackson-core-2.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jackson-databind-2.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jackson-module-jaxb-annotations-2.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/javaGeom-0.11.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/javase-2.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/javax.mail-1.5.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jboss-logging-3.2.1.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jcl-over-slf4j-1.7.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jedis-2.5.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/joda-time-2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jstl-1.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jtds-1.3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/jul-to-slf4j-1.7.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/junit-4.11.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/log4j-1.2.17.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/mail-1.4.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/metadata-extractor-2.6.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/mybatis-3.2.8.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/mybatis-spring-1.2.3.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/mysql-connector-java-5.1.30.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/ojdbc14-10.2.0.4.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/poi-3.9.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/poi-ooxml-3.9.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/poi-ooxml-schemas-3.9.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/shiro-cas-1.2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/shiro-core-1.2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/shiro-ehcache-1.2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/shiro-spring-1.2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/shiro-web-1.2.6.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/sitemesh-2.4.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/slf4j-api-1.7.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/slf4j-log4j12-1.7.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-aop-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-beans-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-context-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-context-support-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-core-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-expression-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-jdbc-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-orm-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-oxm-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-security-config-3.2.3.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-security-core-3.2.3.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-security-crypto-3.2.3.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-security-web-3.2.3.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-test-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-tx-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-web-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/spring-webmvc-4.1.9.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/standard-1.1.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/stax-api-1.0.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/thumbnailator-0.4.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/validation-api-1.1.0.Final.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xercesImpl-2.8.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xml-apis-1.3.04.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xml-apis-ext-1.3.04.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xmlbeans-2.3.0.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xmlgraphics-commons-1.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xmlpull-1.1.3.1.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xmpcore-5.1.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xpp3_min-1.1.4c.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/lib/xstream-1.4.7.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/javax.mail-api-1.6.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-context-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-context-support-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-data-commons-2.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-boot-starter-data-jpa-2.3.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-webmvc-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-security-web-5.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-web-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-boot-starter-security-2.3.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-security-acl-5.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-boot-2.3.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-beans-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-security-config-5.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-core-5.2.11.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-boot-starter-2.3.6.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-security-taglibs-5.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/springfox-spring-web-2.9.2.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-plugin-metadata-1.2.0.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-data-jpa-2.3.5.RELEASE.jar
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/shopizer/WEB-INF/lib/spring-boot-starter-actuator-2.3.6.RELEASE.jar
  #  - ./java-benchmarks/java-sec-code/spring-web-6.1.4.jar
#  spring-context-support-5.1.4.RELEASE.jar

#appClassPath: java-benchmarks/java-sec-code/target/classes
appClassPath:
  - /home/haocheng/Z_personal/Research/projects/Benchmark_FlowDroid/jeesite/WEB-INF/classes
#  - ./java-benchmarks/java-sec-code-new/java-sec-code/demo/target/classes
mainClass: synthetic.method.dummyMainClass
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: true
scope: REACHABLE
nativeModel:  false
planFile: null
analyses:
  #  ir-dumper: ;
  #  pta: cs:ci;implicit-entries:true;merge-string-constants:null;reflection-inference:solar;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:config/common/taint-config.yml;
  #  pta: cs:ci;taint-config:config/common/taint-config.yml;
  #  pta: cs:ci;plugins:[pascal.taie.analysis.pta.plugin.taint.SpringBootHandler,pascal.taie.analysis.pta.plugin.taint.DependencyInjectionHandler];implicit-entries:true;distinguish-string-constants:null;reflection-inference:solar;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:taint-config.yml;
  #  pta: cs:ci;plugins:[pascal.taie.analysis.pta.plugin.taint.SpringBootHandler,pascal.taie.analysis.pta.plugin.taint.DependencyInjectionHandler];implicit-entries:true;distinguish-string-constants:null;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:config/common/taint-config.yml;
  pta: cs:3-call;reflection-inference:solar;implicit-entries:false;taint-config:config/common/jeesite/jeesite1.yml;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
